// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiWEeOhPFkJXNrnHwrhGYJ0X-BvFo561U',
    appId: '1:613069796434:web:5d0e4743b0db1ed709db8b',
    messagingSenderId: '613069796434',
    projectId: 'mynotes-dreadx',
    authDomain: 'mynotes-dreadx.firebaseapp.com',
    storageBucket: 'mynotes-dreadx.firebasestorage.app',
    measurementId: 'G-JJ76BZF5V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7H3YGuH8hj3FA42RK1MleWzIos-3F08',
    appId: '1:613069796434:android:fdfd5cbd6dca689b09db8b',
    messagingSenderId: '613069796434',
    projectId: 'mynotes-dreadx',
    storageBucket: 'mynotes-dreadx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNPetnvj3M-B9SR-kHS0Mmft9x4K8DIe4',
    appId: '1:613069796434:ios:764d92a1974eb3ac09db8b',
    messagingSenderId: '613069796434',
    projectId: 'mynotes-dreadx',
    storageBucket: 'mynotes-dreadx.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNPetnvj3M-B9SR-kHS0Mmft9x4K8DIe4',
    appId: '1:613069796434:ios:764d92a1974eb3ac09db8b',
    messagingSenderId: '613069796434',
    projectId: 'mynotes-dreadx',
    storageBucket: 'mynotes-dreadx.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiWEeOhPFkJXNrnHwrhGYJ0X-BvFo561U',
    appId: '1:613069796434:web:a7f00a01c18d743309db8b',
    messagingSenderId: '613069796434',
    projectId: 'mynotes-dreadx',
    authDomain: 'mynotes-dreadx.firebaseapp.com',
    storageBucket: 'mynotes-dreadx.firebasestorage.app',
    measurementId: 'G-BJKEBL746W',
  );
}
